### ISSUE TITLE
add plotting to make_gain_multithreaded.py

### ISSUE THREAD

**Issue by rvweeren** [cgroeneveld/lodess#5]
Feature request: Add back plotting functionality like in make_gain_screenv2.py. Example included:
![image](https://user-images.githubusercontent.com/3879473/151049488-b0c7038b-016e-4e7f-a11d-1fa50c3123f2.png)

﻿﻿

**Comment by cgroeneveld** [comment]
It isn't a straight forward fix, as multithreading and block-division basically means that at no point the full array is in memory. Maybe I can add it with the restriction that it is run in single-thread mode, or maybe only after the fact. Or maybe, it could be implemented as a separate code.

**Comment by cgroeneveld** [comment]
Fixed.
