### ISSUE TITLE
check for directions outside screen FoV make_gain_multithreaded.py

### ISSUE THREAD

**Issue by rvweeren** [cgroeneveld/lodess#6]
Feature request: check for directions in the H5 that are outside screen FoV in make_gain_multithreaded.py and then exit with a clear error message to the user. Currently, if this happens it gives a rather obscure error message.

**Comment by cgroeneveld** [comment]
Do you maybe have an example call/H5 file somewhere?

**Comment by rvweeren** [comment]
I realize the error happens in the plotting code (option --plotsfortesting), so this needs to be addressed once we add the plotting code (this is thus related to #5) 

('Making screen with shape', (481, 25, 75, 4, 64, 64))
Processing frequency slot 0
('Doing', 'CS001HBA0')
('Doing', 'CS001HBA1')
('Doing', 'CS002HBA0')
('Doing', 'CS002HBA1')
('Doing', 'CS003HBA0')
Traceback (most recent call last):
  File "/net/rijn/data2/rvweeren/LoTSS_ClusterCAL/make_gain_screenv2.py", line 576, in <module>
    plt.scatter(RA_X, DEC_Y, s=symsize, edgecolors='black', vmin=minmaxr[0], vmax=minmaxr[1], c=np.real(gains[timid,ifreq, h5_stations.index(pltstation),:, 0]), cmap='gnuplot2')
  File "/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 3475, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/opt/lofar/pyenv-py2/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 4293, in scatter
    .format(c.shape, x.size, y.size))
ValueError: c of shape (28,) not acceptable as a color sequence for x with size 8, y with size 8
Closing remaining open files:/net/rijn2/data1/rvweeren/h5collection/merged_selfcalcyle_2022jan.h5...done/net/rijn2/data1/rvweeren/h5collection/merged_selfcalcyle_2022jan.h5...done

python /net/rijn/data2/rvweeren/LoTSS_ClusterCAL/make_gain_screenv2.py --ms=/net/rijn2/data2/rvweeren/ELAIS_store/sub6asec_L686962_SB001_uv_12CFFDDA8t_121MHz.ms.sub.shift.avg.apply_infield.avg4ch.ms --size=64 --boxwidth=1.0 --freqdownsamplefactor=5 --H5file=/net/rijn2/data1/rvweeren/h5collection/merged_selfcalcyle_2022jan.h5 --smoothamps --FITSscreen=smoothscreenPython3_64h.fits --plotsfortesting

**Comment by cgroeneveld** [comment]
Fixed, as far as I know
